In [30]:
# Import Dependencies
import pandas as pd

In [31]:
data1_csv = "Output/data1_clean.csv"
data2_csv = "Output/data2_clean.csv"

In [32]:
data1_df = pd.read_csv(data1_csv)
data2_df = pd.read_csv(data2_csv)

In [33]:
data1_df.head()

,Control of institution,State,Variable,SUM,MIN,MAX,AVG
0,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032"
1,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245"
2,Public,Kansas,"Grand total - 4-year institutions, Completers ...","2,213","2,213","2,213","2,213"
3,Public,Kansas,Grand total - Bachelor's or equiv subcohort (4...,"2,213","2,213","2,213","2,213"
4,Public,Kansas,In-district average tuition for full-time unde...,"9,579","9,579","9,579","9,579"

In [34]:
data2_df.head()

,Control of institution,State,Variable,SUM,MIN,MAX,AVG
0,Public,Kansas,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"
1,Public,Kansas,Total number of undergraduates - financial aid...,"19,262","19,262","19,262","19,262"
2,Public,Kansas,"Grand total - 4-year institutions, Completers ...","2,202","2,202","2,202","2,202"
3,Public,Kansas,Grand total - Bachelor's or equiv subcohort (4...,"2,202","2,202","2,202","2,202"
4,Public,Kansas,In-district average tuition for full-time unde...,"9,818","9,818","9,818","9,818"

In [35]:
# Merge the two DataFrames together based on the State they share
crypto_df = pd.merge(data1_df, data2_df, on="State")
crypto_df.head(300)

,Control of institution_x,State,Variable_x,SUM_x,MIN_x,MAX_x,AVG_x,Control of institution_y,Variable_y,SUM_y,MIN_y,MAX_y,AVG_y
0,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"
1,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Total number of undergraduates - financial aid...,"19,262","19,262","19,262","19,262"
2,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"Grand total - 4-year institutions, Completers ...","2,202","2,202","2,202","2,202"
3,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Grand total - Bachelor's or equiv subcohort (4...,"2,202","2,202","2,202","2,202"
4,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district average tuition for full-time unde...,"9,818","9,818","9,818","9,818"
5,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state average tuition for full-time undergr...,"9,818","9,818","9,818","9,818"
6,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state average tuition for full-time und...,"25,586","25,586","25,586","25,586"
7,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district average tuition full-time graduate...,"9,716","9,716","9,716","9,716"
8,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state average tuition full-time graduates -...,"9,716","9,716","9,716","9,716"
9,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state average tuition full-time graduat...,"22,730","22,730","22,730","22,730"
10,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state required fees for full-time gradu...,988,988,988,988
11,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state required fees for full-time graduates...,988,988,988,988
12,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district required fees for full-time gradua...,988,988,988,988
13,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state required fees for full-time under...,"1,006","1,006","1,006","1,006"
14,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state required fees for full-time undergrad...,"1,006","1,006","1,006","1,006"
15,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district required fees for full-time underg...,"1,006","1,006","1,006","1,006"
16,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Books and supplies 2017-18 - (17),NaN,NaN,NaN,NaN
17,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"On campus, room and board 2017-18 - (17)",NaN,NaN,NaN,NaN
18,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"On campus, other expenses 2017-18 - (17)",NaN,NaN,NaN,NaN
19,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"Off campus (not with family), room and board ...",NaN,NaN,NaN,NaN
20,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Full-time first-time degree/certificate-seekin...,"4,079","4,079","4,079","4,079"
21,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Total entering students at the undergraduate l...,"5,645","5,645","5,645","5,645"
22,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Current year GRS cohort as a percent of enteri...,72,72,72,72
23,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"
24,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Total number of undergraduates - financial aid...,"19,262","19,262","19,262","19,262"
25,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,"Grand total - 4-year institutions, Completers ...","2,202","2,202","2,202","2,202"
26,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Grand total - Bachelor's or equiv subcohort (4...,"2,202","2,202","2,202","2,202"
27,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,In-district average tuition for full-time unde...,"9,818","9,818","9,818","9,818"
28,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,In-state average tuition for full-time undergr...,"9,818","9,818","9,818","9,818"
29,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Out-of-state average tuition for full-time und...,"25,586","25,586","25,586","25,586"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,Public,Kansas,In-state required fees for full-time undergrad...,970,970,970,970,Public,"On campus, room and board 2017-18 - (17)",NaN,NaN,NaN,NaN
271,Public,Kansas,In-state required fees for full-time undergrad...,970,970,970,970,Public,"On campus, other expenses 2017-18 - (17)",NaN,NaN,NaN,NaN
272,Public,Kansas,In-state required fees for full-time undergrad...,970,970,970,970,Public,"Off campus (not with family), room and board ...",NaN,NaN,NaN,NaN
273,Public,Kansas,In-state required fees for full-time undergrad...,970,970,970,970,Public,Full-time first-time degree/certificate-seekin...,"4,079","4,079","4,079","4,079"
274,Public,Kansas,In-state required fees for full-time undergrad...,970,970,970,970,Public,Total entering students at the undergraduate l...,"5,645","5,645","5,645","5,645"
275,Public,Kansas,In-state required fees for full-time undergrad...,970,970,970,970,Public,Current year GRS cohort as a percent of enteri...,72,72,72,72
276,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"
277,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Total number of undergraduates - financial aid...,"19,262","19,262","19,262","19,262"
278,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,"Grand total - 4-year institutions, Completers ...","2,202","2,202","2,202","2,202"
279,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Grand total - Bachelor's or equiv subcohort (4...,"2,202","2,202","2,202","2,202"
280,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-district average tuition for full-time unde...,"9,818","9,818","9,818","9,818"
281,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-state average tuition for full-time undergr...,"9,818","9,818","9,818","9,818"
282,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Out-of-state average tuition for full-time und...,"25,586","25,586","25,586","25,586"
283,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-district average tuition full-time graduate...,"9,716","9,716","9,716","9,716"
284,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-state average tuition full-time graduates -...,"9,716","9,716","9,716","9,716"
285,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Out-of-state average tuition full-time graduat...,"22,730","22,730","22,730","22,730"
286,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Out-of-state required fees for full-time gradu...,988,988,988,988
287,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-state required fees for full-time graduates...,988,988,988,988
288,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-district required fees for full-time gradua...,988,988,988,988
289,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Out-of-state required fees for full-time under...,"1,006","1,006","1,006","1,006"
290,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-state required fees for full-time undergrad...,"1,006","1,006","1,006","1,006"
291,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,In-district required fees for full-time underg...,"1,006","1,006","1,006","1,006"
292,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Books and supplies 2017-18 - (17),NaN,NaN,NaN,NaN
293,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,"On campus, room and board 2017-18 - (17)",NaN,NaN,NaN,NaN
294,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,"On campus, other expenses 2017-18 - (17)",NaN,NaN,NaN,NaN
295,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,"Off campus (not with family), room and board ...",NaN,NaN,NaN,NaN
296,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Full-time first-time degree/certificate-seekin...,"4,079","4,079","4,079","4,079"
297,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Total entering students at the undergraduate l...,"5,645","5,645","5,645","5,645"
298,Public,Kansas,Out-of-state required fees for full-time under...,970,970,970,970,Public,Current year GRS cohort as a percent of enteri...,72,72,72,72
299,Public,Kansas,In-district required fees for full-time gradua...,958,958,958,958,Public,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"

In [40]:
# Merge two dataframes using an outer join
crypto_df = pd.merge(data1_df, data2_df, on="State", how="outer")
crypto_df

,Control of institution_x,State,Variable_x,SUM_x,MIN_x,MAX_x,AVG_x,Control of institution_y,Variable_y,SUM_y,MIN_y,MAX_y,AVG_y
0,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"
1,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Total number of undergraduates - financial aid...,"19,262","19,262","19,262","19,262"
2,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"Grand total - 4-year institutions, Completers ...","2,202","2,202","2,202","2,202"
3,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Grand total - Bachelor's or equiv subcohort (4...,"2,202","2,202","2,202","2,202"
4,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district average tuition for full-time unde...,"9,818","9,818","9,818","9,818"
5,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state average tuition for full-time undergr...,"9,818","9,818","9,818","9,818"
6,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state average tuition for full-time und...,"25,586","25,586","25,586","25,586"
7,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district average tuition full-time graduate...,"9,716","9,716","9,716","9,716"
8,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state average tuition full-time graduates -...,"9,716","9,716","9,716","9,716"
9,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state average tuition full-time graduat...,"22,730","22,730","22,730","22,730"
10,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state required fees for full-time gradu...,988,988,988,988
11,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state required fees for full-time graduates...,988,988,988,988
12,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district required fees for full-time gradua...,988,988,988,988
13,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Out-of-state required fees for full-time under...,"1,006","1,006","1,006","1,006"
14,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-state required fees for full-time undergrad...,"1,006","1,006","1,006","1,006"
15,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,In-district required fees for full-time underg...,"1,006","1,006","1,006","1,006"
16,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Books and supplies 2017-18 - (17),NaN,NaN,NaN,NaN
17,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"On campus, room and board 2017-18 - (17)",NaN,NaN,NaN,NaN
18,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"On campus, other expenses 2017-18 - (17)",NaN,NaN,NaN,NaN
19,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,"Off campus (not with family), room and board ...",NaN,NaN,NaN,NaN
20,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Full-time first-time degree/certificate-seekin...,"4,079","4,079","4,079","4,079"
21,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Total entering students at the undergraduate l...,"5,645","5,645","5,645","5,645"
22,Public,Kansas,Total number of full-time first-time degree/ce...,"4,032","4,032","4,032","4,032",Public,Current year GRS cohort as a percent of enteri...,72,72,72,72
23,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Total number of full-time first-time degree/ce...,"4,130","4,130","4,130","4,130"
24,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Total number of undergraduates - financial aid...,"19,262","19,262","19,262","19,262"
25,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,"Grand total - 4-year institutions, Completers ...","2,202","2,202","2,202","2,202"
26,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Grand total - Bachelor's or equiv subcohort (4...,"2,202","2,202","2,202","2,202"
27,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,In-district average tuition for full-time unde...,"9,818","9,818","9,818","9,818"
28,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,In-state average tuition for full-time undergr...,"9,818","9,818","9,818","9,818"
29,Public,Kansas,Total number of undergraduates - financial aid...,"19,245","19,245","19,245","19,245",Public,Out-of-state average tuition for full-time und...,"25,586","25,586","25,586","25,586"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,Books and supplies 2017-18 - (17),NaN,NaN,NaN,NaN
1903,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,"On campus, room and board 2017-18 - (17)",NaN,NaN,NaN,NaN
1904,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,"On campus, other expenses 2017-18 - (17)",NaN,NaN,NaN,NaN
1905,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,"Off campus (not with family), room and board ...",NaN,NaN,NaN,NaN
1906,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,Full-time first-time degree/certificate-seekin...,"4,883","4,883","4,883","4,883"
1907,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,Total entering students at the undergraduate l...,"5,716","5,716","5,716","5,716"
1908,Public,Nebraska,Total entering students at the undergraduate l...,"5,551","5,551","5,551","5,551",Public,Current year GRS cohort as a percent of enteri...,85,85,85,85
1909,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Total number of full-time first-time degree/ce...,"4,833","4,833","4,833","4,833"
1910,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Total number of undergraduates - financial aid...,"20,833","20,833","20,833","20,833"
1911,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,"Grand total - 4-year institutions, Completers ...","2,756","2,756","2,756","2,756"
1912,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Grand total - Bachelor's or equiv subcohort (4...,"2,756","2,756","2,756","2,756"
1913,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-district average tuition for full-time unde...,"7,125","7,125","7,125","7,125"
1914,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-state average tuition for full-time undergr...,"7,125","7,125","7,125","7,125"
1915,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Out-of-state average tuition for full-time und...,"22,425","22,425","22,425","22,425"
1916,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-district average tuition full-time graduate...,"7,518","7,518","7,518","7,518"
1917,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-state average tuition full-time graduates -...,"7,518","7,518","7,518","7,518"
1918,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Out-of-state average tuition full-time graduat...,"22,425","22,425","22,425","22,425"
1919,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Out-of-state required fees for full-time gradu...,"1,853","1,853","1,853","1,853"
1920,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-state required fees for full-time graduates...,"1,853","1,853","1,853","1,853"
1921,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-district required fees for full-time gradua...,"1,853","1,853","1,853","1,853"
1922,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Out-of-state required fees for full-time under...,"1,853","1,853","1,853","1,853"
1923,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-state required fees for full-time undergrad...,"1,853","1,853","1,853","1,853"
1924,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,In-district required fees for full-time underg...,"1,853","1,853","1,853","1,853"
1925,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Books and supplies 2017-18 - (17),NaN,NaN,NaN,NaN
1926,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,"On campus, room and board 2017-18 - (17)",NaN,NaN,NaN,NaN
1927,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,"On campus, other expenses 2017-18 - (17)",NaN,NaN,NaN,NaN
1928,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,"Off campus (not with family), room and board ...",NaN,NaN,NaN,NaN
1929,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Full-time first-time degree/certificate-seekin...,"4,883","4,883","4,883","4,883"
1930,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Total entering students at the undergraduate l...,"5,716","5,716","5,716","5,716"
1931,Public,Nebraska,Current year GRS cohort as a percent of enteri...,83,83,83,83,Public,Current year GRS cohort as a percent of enteri...,85,85,85,85